### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by tnrich** [ThomasR/JSON.sortify#11]
Hey there, 

I'm just wondering if there would be some way you could change the lib to be compiled down to an earlier js version. Currently uglify is choking on the ()=> syntax:
```
static/js/main.39077179.js from UglifyJs
Unexpected token: operator (>) [./~/json.sortify/lib/index.js:29,0][static/js/main.39077179.js:127447,20]
```

Thank you!

**Comment by tnrich** [comment]
I might be wrong but I think you should point to `./dist`  in your index.js file. 
Currently it is pointing to:
```
module.exports = require('./lib');
```
Or, maybe even better would be to do 
```
"main": "dist",
"es": "lib"
```
in your `package.json`

Let me know what you think. Thanks!

**Comment by tnrich** [comment]
Here's someone from create-react-app saying that the issue is with json.sortify:
https://github.com/facebookincubator/create-react-app/issues/2945

**Comment by ThomasR** [comment]
Thanks for reporting and sorry for the delay.

> Or, maybe even better would be to do
>
>    "main": "dist",
>    "es": "lib"

What is `"es"` good for? I guess the `lib` folder is not needed at all, and I consider cleaning up the published files. Now that I think about it, the cleanest way might be to save the compiled version as index.js and just ignore everything else. What do you think?

**Comment by tnrich** [comment]
The es property in a package.json is meant to point to an es6 compatible version of the code. Not really necessary in this case. 

Given that your tool fits in a single file, I would have your index.js be the normal file and have a dist/index.js which you point to like `"main": "dist"`

I think it would be a little odd to have the index.js be the compiled version. 

Just my two cents :) 

Thanks for fixing it!

**Comment by ThomasR** [comment]
Please test if v2.2.2 resolves your issue

**Comment by tnrich** [comment]
Looks good to me! Thanks @ThomasR
