### ISSUE TITLE
Uncaught ReferenceError: definition is not defined

### ISSUE THREAD

**Issue by AnimaLupi** [ThomasR/JSON.sortify#2]
Hello,

I'm getting the error

`JSON.sortify.js:1 Uncaught ReferenceError: definition is not defined`

on latest version. I hadn't the same problem on earlier version.

Do I need to do anything different (I seems to comply with the docs, though) or something went wrong with the build?

Thank you!

Andrea

**Comment by ThomasR** [comment]
Thank you! I did a half-assed job on renaming a variable, just before releasing.
Note to myself: Don’t.

This is a perfect example for the benefit of tests. -> GH-3

**Comment by ThomasR** [comment]
@AnimaLupi
Please try version 2.0.1, everything should be fine now.

**Comment by AnimaLupi** [comment]
Error is gone, thank you!
